version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: echo
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5080:5432"
    networks:
      network:
        ipv4_address: 172.29.5.4

  dotnet_app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet_app
    restart: always
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "
        export PATH="$PATH:/root/.dotnet/tools" &&
        dotnet tool install --global dotnet-ef &&
        dotnet ef database update --project Echo &&
        dotnet run --urls=http://0.0.0.0:5000 --project Echo
      "
    ports:
      - "5081:5000"
    networks:
      network:
        ipv4_address: 172.29.5.5

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.5.255
