version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: echo
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5002:5432"
    networks:
      network:
        ipv4_address: 172.29.5.4

  dotnet_app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet_app
    restart: always
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "
        cd Echo
        dotnet tool install dotnet-ef --version 8.0.1 && 
        dotnet dotnet-ef migrations add InitialCreate || true && 
        dotnet dotnet-ef database update &&
        dotnet run
      "
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      network:
        ipv4_address: 172.29.5.5

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.5.255
